[package]
name = "learn-rust-by-example"
version = "0.1.0"
edition = "2021"
author = "SangShengJie"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
